/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.Exquery;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Program;
import org.xtext.example.mydsl.myDsl.Prologdsl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Prologdsl</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.PrologdslImpl#getProgam <em>Progam</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.PrologdslImpl#getExquery <em>Exquery</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PrologdslImpl extends MinimalEObjectImpl.Container implements Prologdsl
{
  /**
   * The cached value of the '{@link #getProgam() <em>Progam</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProgam()
   * @generated
   * @ordered
   */
  protected Program progam;

  /**
   * The cached value of the '{@link #getExquery() <em>Exquery</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExquery()
   * @generated
   * @ordered
   */
  protected Exquery exquery;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrologdslImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.PROLOGDSL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Program getProgam()
  {
    return progam;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetProgam(Program newProgam, NotificationChain msgs)
  {
    Program oldProgam = progam;
    progam = newProgam;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.PROLOGDSL__PROGAM, oldProgam, newProgam);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setProgam(Program newProgam)
  {
    if (newProgam != progam)
    {
      NotificationChain msgs = null;
      if (progam != null)
        msgs = ((InternalEObject)progam).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.PROLOGDSL__PROGAM, null, msgs);
      if (newProgam != null)
        msgs = ((InternalEObject)newProgam).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.PROLOGDSL__PROGAM, null, msgs);
      msgs = basicSetProgam(newProgam, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.PROLOGDSL__PROGAM, newProgam, newProgam));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Exquery getExquery()
  {
    return exquery;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExquery(Exquery newExquery, NotificationChain msgs)
  {
    Exquery oldExquery = exquery;
    exquery = newExquery;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.PROLOGDSL__EXQUERY, oldExquery, newExquery);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExquery(Exquery newExquery)
  {
    if (newExquery != exquery)
    {
      NotificationChain msgs = null;
      if (exquery != null)
        msgs = ((InternalEObject)exquery).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.PROLOGDSL__EXQUERY, null, msgs);
      if (newExquery != null)
        msgs = ((InternalEObject)newExquery).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.PROLOGDSL__EXQUERY, null, msgs);
      msgs = basicSetExquery(newExquery, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.PROLOGDSL__EXQUERY, newExquery, newExquery));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.PROLOGDSL__PROGAM:
        return basicSetProgam(null, msgs);
      case MyDslPackage.PROLOGDSL__EXQUERY:
        return basicSetExquery(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.PROLOGDSL__PROGAM:
        return getProgam();
      case MyDslPackage.PROLOGDSL__EXQUERY:
        return getExquery();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.PROLOGDSL__PROGAM:
        setProgam((Program)newValue);
        return;
      case MyDslPackage.PROLOGDSL__EXQUERY:
        setExquery((Exquery)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.PROLOGDSL__PROGAM:
        setProgam((Program)null);
        return;
      case MyDslPackage.PROLOGDSL__EXQUERY:
        setExquery((Exquery)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.PROLOGDSL__PROGAM:
        return progam != null;
      case MyDslPackage.PROLOGDSL__EXQUERY:
        return exquery != null;
    }
    return super.eIsSet(featureID);
  }

} //PrologdslImpl
