/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.Atom;
import org.xtext.example.mydsl.myDsl.ListOpt1;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Rest;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rest</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.RestImpl#getOpt <em>Opt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.RestImpl#getAtom <em>Atom</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.RestImpl#getNextatom <em>Nextatom</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RestImpl extends MinimalEObjectImpl.Container implements Rest
{
  /**
   * The cached value of the '{@link #getOpt() <em>Opt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOpt()
   * @generated
   * @ordered
   */
  protected ListOpt1 opt;

  /**
   * The cached value of the '{@link #getAtom() <em>Atom</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAtom()
   * @generated
   * @ordered
   */
  protected Atom atom;

  /**
   * The cached value of the '{@link #getNextatom() <em>Nextatom</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNextatom()
   * @generated
   * @ordered
   */
  protected EList<Atom> nextatom;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RestImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.REST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ListOpt1 getOpt()
  {
    return opt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOpt(ListOpt1 newOpt, NotificationChain msgs)
  {
    ListOpt1 oldOpt = opt;
    opt = newOpt;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.REST__OPT, oldOpt, newOpt);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOpt(ListOpt1 newOpt)
  {
    if (newOpt != opt)
    {
      NotificationChain msgs = null;
      if (opt != null)
        msgs = ((InternalEObject)opt).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.REST__OPT, null, msgs);
      if (newOpt != null)
        msgs = ((InternalEObject)newOpt).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.REST__OPT, null, msgs);
      msgs = basicSetOpt(newOpt, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.REST__OPT, newOpt, newOpt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Atom getAtom()
  {
    return atom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAtom(Atom newAtom, NotificationChain msgs)
  {
    Atom oldAtom = atom;
    atom = newAtom;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.REST__ATOM, oldAtom, newAtom);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAtom(Atom newAtom)
  {
    if (newAtom != atom)
    {
      NotificationChain msgs = null;
      if (atom != null)
        msgs = ((InternalEObject)atom).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.REST__ATOM, null, msgs);
      if (newAtom != null)
        msgs = ((InternalEObject)newAtom).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.REST__ATOM, null, msgs);
      msgs = basicSetAtom(newAtom, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.REST__ATOM, newAtom, newAtom));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Atom> getNextatom()
  {
    if (nextatom == null)
    {
      nextatom = new EObjectContainmentEList<Atom>(Atom.class, this, MyDslPackage.REST__NEXTATOM);
    }
    return nextatom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.REST__OPT:
        return basicSetOpt(null, msgs);
      case MyDslPackage.REST__ATOM:
        return basicSetAtom(null, msgs);
      case MyDslPackage.REST__NEXTATOM:
        return ((InternalEList<?>)getNextatom()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.REST__OPT:
        return getOpt();
      case MyDslPackage.REST__ATOM:
        return getAtom();
      case MyDslPackage.REST__NEXTATOM:
        return getNextatom();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.REST__OPT:
        setOpt((ListOpt1)newValue);
        return;
      case MyDslPackage.REST__ATOM:
        setAtom((Atom)newValue);
        return;
      case MyDslPackage.REST__NEXTATOM:
        getNextatom().clear();
        getNextatom().addAll((Collection<? extends Atom>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.REST__OPT:
        setOpt((ListOpt1)null);
        return;
      case MyDslPackage.REST__ATOM:
        setAtom((Atom)null);
        return;
      case MyDslPackage.REST__NEXTATOM:
        getNextatom().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.REST__OPT:
        return opt != null;
      case MyDslPackage.REST__ATOM:
        return atom != null;
      case MyDslPackage.REST__NEXTATOM:
        return nextatom != null && !nextatom.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //RestImpl
