/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Folge</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Folge#getAtom <em>Atom</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Folge#getNextatom <em>Nextatom</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFolge()
 * @model
 * @generated
 */
public interface Folge extends EObject
{
  /**
   * Returns the value of the '<em><b>Atom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Atom</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atom</em>' containment reference.
   * @see #setAtom(Atom)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFolge_Atom()
   * @model containment="true"
   * @generated
   */
  Atom getAtom();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Folge#getAtom <em>Atom</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Atom</em>' containment reference.
   * @see #getAtom()
   * @generated
   */
  void setAtom(Atom value);

  /**
   * Returns the value of the '<em><b>Nextatom</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Atom}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nextatom</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nextatom</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFolge_Nextatom()
   * @model containment="true"
   * @generated
   */
  EList<Atom> getNextatom();

} // Folge
