/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.List#getKa <em>Ka</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.List#getAtom <em>Atom</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.List#getRest <em>Rest</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.List#getKz <em>Kz</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getList()
 * @model
 * @generated
 */
public interface List extends EObject
{
  /**
   * Returns the value of the '<em><b>Ka</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ka</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ka</em>' attribute.
   * @see #setKa(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getList_Ka()
   * @model
   * @generated
   */
  String getKa();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.List#getKa <em>Ka</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ka</em>' attribute.
   * @see #getKa()
   * @generated
   */
  void setKa(String value);

  /**
   * Returns the value of the '<em><b>Atom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Atom</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atom</em>' containment reference.
   * @see #setAtom(Atom)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getList_Atom()
   * @model containment="true"
   * @generated
   */
  Atom getAtom();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.List#getAtom <em>Atom</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Atom</em>' containment reference.
   * @see #getAtom()
   * @generated
   */
  void setAtom(Atom value);

  /**
   * Returns the value of the '<em><b>Rest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rest</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rest</em>' containment reference.
   * @see #setRest(Rest)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getList_Rest()
   * @model containment="true"
   * @generated
   */
  Rest getRest();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.List#getRest <em>Rest</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rest</em>' containment reference.
   * @see #getRest()
   * @generated
   */
  void setRest(Rest value);

  /**
   * Returns the value of the '<em><b>Kz</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Kz</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kz</em>' attribute.
   * @see #setKz(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getList_Kz()
   * @model
   * @generated
   */
  String getKz();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.List#getKz <em>Kz</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kz</em>' attribute.
   * @see #getKz()
   * @generated
   */
  void setKz(String value);

} // List
