/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.PrologdslImpl <em>Prologdsl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.PrologdslImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPrologdsl()
   * @generated
   */
  int PROLOGDSL = 0;

  /**
   * The feature id for the '<em><b>Progam</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROLOGDSL__PROGAM = 0;

  /**
   * The feature id for the '<em><b>Exquery</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROLOGDSL__EXQUERY = 1;

  /**
   * The number of structural features of the '<em>Prologdsl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROLOGDSL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ProgramImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 1;

  /**
   * The feature id for the '<em><b>Clause</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__CLAUSE = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ExqueryImpl <em>Exquery</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ExqueryImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExquery()
   * @generated
   */
  int EXQUERY = 2;

  /**
   * The feature id for the '<em><b>Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXQUERY__QUERY = 0;

  /**
   * The number of structural features of the '<em>Exquery</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXQUERY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.QueryImpl <em>Query</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.QueryImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getQuery()
   * @generated
   */
  int QUERY = 3;

  /**
   * The feature id for the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__PREDICATE = 0;

  /**
   * The feature id for the '<em><b>Nextpredicate</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__NEXTPREDICATE = 1;

  /**
   * The number of structural features of the '<em>Query</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ClauseImpl <em>Clause</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ClauseImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getClause()
   * @generated
   */
  int CLAUSE = 4;

  /**
   * The feature id for the '<em><b>Fact</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLAUSE__FACT = 0;

  /**
   * The feature id for the '<em><b>Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLAUSE__RULE = 1;

  /**
   * The number of structural features of the '<em>Clause</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLAUSE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FactImpl <em>Fact</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FactImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFact()
   * @generated
   */
  int FACT = 5;

  /**
   * The feature id for the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACT__PREDICATE = 0;

  /**
   * The number of structural features of the '<em>Fact</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RuleImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRule()
   * @generated
   */
  int RULE = 6;

  /**
   * The feature id for the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__PREDICATE = 0;

  /**
   * The feature id for the '<em><b>Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__QUERY = 1;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.PredicateImpl <em>Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.PredicateImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPredicate()
   * @generated
   */
  int PREDICATE = 7;

  /**
   * The feature id for the '<em><b>Functor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__FUNCTOR = 0;

  /**
   * The feature id for the '<em><b>Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__TERM = 1;

  /**
   * The feature id for the '<em><b>Nextterm</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__NEXTTERM = 2;

  /**
   * The number of structural features of the '<em>Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FunctorImpl <em>Functor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FunctorImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFunctor()
   * @generated
   */
  int FUNCTOR = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTOR__NAME = 0;

  /**
   * The number of structural features of the '<em>Functor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTOR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TermImpl <em>Term</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TermImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTerm()
   * @generated
   */
  int TERM = 9;

  /**
   * The feature id for the '<em><b>Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM__TERM = 0;

  /**
   * The number of structural features of the '<em>Term</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AtomImpl <em>Atom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AtomImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAtom()
   * @generated
   */
  int ATOM = 10;

  /**
   * The feature id for the '<em><b>At</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM__AT = 0;

  /**
   * The number of structural features of the '<em>Atom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ListImpl <em>List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ListImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getList()
   * @generated
   */
  int LIST = 11;

  /**
   * The feature id for the '<em><b>Ka</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST__KA = 0;

  /**
   * The feature id for the '<em><b>Atom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST__ATOM = 1;

  /**
   * The feature id for the '<em><b>Rest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST__REST = 2;

  /**
   * The feature id for the '<em><b>Kz</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST__KZ = 3;

  /**
   * The number of structural features of the '<em>List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RestImpl <em>Rest</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RestImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRest()
   * @generated
   */
  int REST = 12;

  /**
   * The feature id for the '<em><b>Opt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST__OPT = 0;

  /**
   * The feature id for the '<em><b>Atom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST__ATOM = 1;

  /**
   * The feature id for the '<em><b>Nextatom</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST__NEXTATOM = 2;

  /**
   * The number of structural features of the '<em>Rest</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ListOpt1Impl <em>List Opt1</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ListOpt1Impl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getListOpt1()
   * @generated
   */
  int LIST_OPT1 = 13;

  /**
   * The feature id for the '<em><b>Atom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_OPT1__ATOM = 0;

  /**
   * The number of structural features of the '<em>List Opt1</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_OPT1_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ListOpt2Impl <em>List Opt2</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ListOpt2Impl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getListOpt2()
   * @generated
   */
  int LIST_OPT2 = 14;

  /**
   * The feature id for the '<em><b>Opt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_OPT2__OPT = REST__OPT;

  /**
   * The feature id for the '<em><b>Atom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_OPT2__ATOM = REST__ATOM;

  /**
   * The feature id for the '<em><b>Nextatom</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_OPT2__NEXTATOM = REST__NEXTATOM;

  /**
   * The number of structural features of the '<em>List Opt2</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_OPT2_FEATURE_COUNT = REST_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ListOpt3Impl <em>List Opt3</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ListOpt3Impl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getListOpt3()
   * @generated
   */
  int LIST_OPT3 = 15;

  /**
   * The feature id for the '<em><b>Opt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_OPT3__OPT = REST__OPT;

  /**
   * The feature id for the '<em><b>Atom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_OPT3__ATOM = REST__ATOM;

  /**
   * The feature id for the '<em><b>Nextatom</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_OPT3__NEXTATOM = REST__NEXTATOM;

  /**
   * The number of structural features of the '<em>List Opt3</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_OPT3_FEATURE_COUNT = REST_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FolgeImpl <em>Folge</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FolgeImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFolge()
   * @generated
   */
  int FOLGE = 16;

  /**
   * The feature id for the '<em><b>Atom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOLGE__ATOM = 0;

  /**
   * The feature id for the '<em><b>Nextatom</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOLGE__NEXTATOM = 1;

  /**
   * The number of structural features of the '<em>Folge</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOLGE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Prologdsl <em>Prologdsl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prologdsl</em>'.
   * @see org.xtext.example.mydsl.myDsl.Prologdsl
   * @generated
   */
  EClass getPrologdsl();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Prologdsl#getProgam <em>Progam</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Progam</em>'.
   * @see org.xtext.example.mydsl.myDsl.Prologdsl#getProgam()
   * @see #getPrologdsl()
   * @generated
   */
  EReference getPrologdsl_Progam();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Prologdsl#getExquery <em>Exquery</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exquery</em>'.
   * @see org.xtext.example.mydsl.myDsl.Prologdsl#getExquery()
   * @see #getPrologdsl()
   * @generated
   */
  EReference getPrologdsl_Exquery();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.xtext.example.mydsl.myDsl.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Program#getClause <em>Clause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Clause</em>'.
   * @see org.xtext.example.mydsl.myDsl.Program#getClause()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Clause();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Exquery <em>Exquery</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exquery</em>'.
   * @see org.xtext.example.mydsl.myDsl.Exquery
   * @generated
   */
  EClass getExquery();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Exquery#getQuery <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Query</em>'.
   * @see org.xtext.example.mydsl.myDsl.Exquery#getQuery()
   * @see #getExquery()
   * @generated
   */
  EReference getExquery_Query();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Query <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query</em>'.
   * @see org.xtext.example.mydsl.myDsl.Query
   * @generated
   */
  EClass getQuery();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Query#getPredicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate</em>'.
   * @see org.xtext.example.mydsl.myDsl.Query#getPredicate()
   * @see #getQuery()
   * @generated
   */
  EReference getQuery_Predicate();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Query#getNextpredicate <em>Nextpredicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Nextpredicate</em>'.
   * @see org.xtext.example.mydsl.myDsl.Query#getNextpredicate()
   * @see #getQuery()
   * @generated
   */
  EReference getQuery_Nextpredicate();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Clause <em>Clause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Clause</em>'.
   * @see org.xtext.example.mydsl.myDsl.Clause
   * @generated
   */
  EClass getClause();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Clause#getFact <em>Fact</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fact</em>'.
   * @see org.xtext.example.mydsl.myDsl.Clause#getFact()
   * @see #getClause()
   * @generated
   */
  EReference getClause_Fact();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Clause#getRule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rule</em>'.
   * @see org.xtext.example.mydsl.myDsl.Clause#getRule()
   * @see #getClause()
   * @generated
   */
  EReference getClause_Rule();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Fact <em>Fact</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fact</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fact
   * @generated
   */
  EClass getFact();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Fact#getPredicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fact#getPredicate()
   * @see #getFact()
   * @generated
   */
  EReference getFact_Predicate();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Rule#getPredicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rule#getPredicate()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Predicate();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Rule#getQuery <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Query</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rule#getQuery()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Query();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Predicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicate</em>'.
   * @see org.xtext.example.mydsl.myDsl.Predicate
   * @generated
   */
  EClass getPredicate();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Predicate#getFunctor <em>Functor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Functor</em>'.
   * @see org.xtext.example.mydsl.myDsl.Predicate#getFunctor()
   * @see #getPredicate()
   * @generated
   */
  EReference getPredicate_Functor();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Predicate#getTerm <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Term</em>'.
   * @see org.xtext.example.mydsl.myDsl.Predicate#getTerm()
   * @see #getPredicate()
   * @generated
   */
  EReference getPredicate_Term();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Predicate#getNextterm <em>Nextterm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Nextterm</em>'.
   * @see org.xtext.example.mydsl.myDsl.Predicate#getNextterm()
   * @see #getPredicate()
   * @generated
   */
  EReference getPredicate_Nextterm();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Functor <em>Functor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Functor</em>'.
   * @see org.xtext.example.mydsl.myDsl.Functor
   * @generated
   */
  EClass getFunctor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Functor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Functor#getName()
   * @see #getFunctor()
   * @generated
   */
  EAttribute getFunctor_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Term <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Term</em>'.
   * @see org.xtext.example.mydsl.myDsl.Term
   * @generated
   */
  EClass getTerm();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Term#getTerm <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Term</em>'.
   * @see org.xtext.example.mydsl.myDsl.Term#getTerm()
   * @see #getTerm()
   * @generated
   */
  EReference getTerm_Term();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Atom <em>Atom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atom</em>'.
   * @see org.xtext.example.mydsl.myDsl.Atom
   * @generated
   */
  EClass getAtom();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Atom#getAt <em>At</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>At</em>'.
   * @see org.xtext.example.mydsl.myDsl.Atom#getAt()
   * @see #getAtom()
   * @generated
   */
  EAttribute getAtom_At();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.List <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List</em>'.
   * @see org.xtext.example.mydsl.myDsl.List
   * @generated
   */
  EClass getList();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.List#getKa <em>Ka</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ka</em>'.
   * @see org.xtext.example.mydsl.myDsl.List#getKa()
   * @see #getList()
   * @generated
   */
  EAttribute getList_Ka();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.List#getAtom <em>Atom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Atom</em>'.
   * @see org.xtext.example.mydsl.myDsl.List#getAtom()
   * @see #getList()
   * @generated
   */
  EReference getList_Atom();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.List#getRest <em>Rest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rest</em>'.
   * @see org.xtext.example.mydsl.myDsl.List#getRest()
   * @see #getList()
   * @generated
   */
  EReference getList_Rest();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.List#getKz <em>Kz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Kz</em>'.
   * @see org.xtext.example.mydsl.myDsl.List#getKz()
   * @see #getList()
   * @generated
   */
  EAttribute getList_Kz();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Rest <em>Rest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rest</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rest
   * @generated
   */
  EClass getRest();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Rest#getOpt <em>Opt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Opt</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rest#getOpt()
   * @see #getRest()
   * @generated
   */
  EReference getRest_Opt();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Rest#getAtom <em>Atom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Atom</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rest#getAtom()
   * @see #getRest()
   * @generated
   */
  EReference getRest_Atom();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Rest#getNextatom <em>Nextatom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Nextatom</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rest#getNextatom()
   * @see #getRest()
   * @generated
   */
  EReference getRest_Nextatom();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ListOpt1 <em>List Opt1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Opt1</em>'.
   * @see org.xtext.example.mydsl.myDsl.ListOpt1
   * @generated
   */
  EClass getListOpt1();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ListOpt1#getAtom <em>Atom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Atom</em>'.
   * @see org.xtext.example.mydsl.myDsl.ListOpt1#getAtom()
   * @see #getListOpt1()
   * @generated
   */
  EReference getListOpt1_Atom();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ListOpt2 <em>List Opt2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Opt2</em>'.
   * @see org.xtext.example.mydsl.myDsl.ListOpt2
   * @generated
   */
  EClass getListOpt2();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ListOpt3 <em>List Opt3</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Opt3</em>'.
   * @see org.xtext.example.mydsl.myDsl.ListOpt3
   * @generated
   */
  EClass getListOpt3();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Folge <em>Folge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Folge</em>'.
   * @see org.xtext.example.mydsl.myDsl.Folge
   * @generated
   */
  EClass getFolge();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Folge#getAtom <em>Atom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Atom</em>'.
   * @see org.xtext.example.mydsl.myDsl.Folge#getAtom()
   * @see #getFolge()
   * @generated
   */
  EReference getFolge_Atom();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Folge#getNextatom <em>Nextatom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Nextatom</em>'.
   * @see org.xtext.example.mydsl.myDsl.Folge#getNextatom()
   * @see #getFolge()
   * @generated
   */
  EReference getFolge_Nextatom();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.PrologdslImpl <em>Prologdsl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.PrologdslImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPrologdsl()
     * @generated
     */
    EClass PROLOGDSL = eINSTANCE.getPrologdsl();

    /**
     * The meta object literal for the '<em><b>Progam</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROLOGDSL__PROGAM = eINSTANCE.getPrologdsl_Progam();

    /**
     * The meta object literal for the '<em><b>Exquery</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROLOGDSL__EXQUERY = eINSTANCE.getPrologdsl_Exquery();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ProgramImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Clause</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__CLAUSE = eINSTANCE.getProgram_Clause();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ExqueryImpl <em>Exquery</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ExqueryImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExquery()
     * @generated
     */
    EClass EXQUERY = eINSTANCE.getExquery();

    /**
     * The meta object literal for the '<em><b>Query</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXQUERY__QUERY = eINSTANCE.getExquery_Query();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.QueryImpl <em>Query</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.QueryImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getQuery()
     * @generated
     */
    EClass QUERY = eINSTANCE.getQuery();

    /**
     * The meta object literal for the '<em><b>Predicate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY__PREDICATE = eINSTANCE.getQuery_Predicate();

    /**
     * The meta object literal for the '<em><b>Nextpredicate</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY__NEXTPREDICATE = eINSTANCE.getQuery_Nextpredicate();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ClauseImpl <em>Clause</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ClauseImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getClause()
     * @generated
     */
    EClass CLAUSE = eINSTANCE.getClause();

    /**
     * The meta object literal for the '<em><b>Fact</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLAUSE__FACT = eINSTANCE.getClause_Fact();

    /**
     * The meta object literal for the '<em><b>Rule</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLAUSE__RULE = eINSTANCE.getClause_Rule();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FactImpl <em>Fact</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FactImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFact()
     * @generated
     */
    EClass FACT = eINSTANCE.getFact();

    /**
     * The meta object literal for the '<em><b>Predicate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACT__PREDICATE = eINSTANCE.getFact_Predicate();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RuleImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Predicate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__PREDICATE = eINSTANCE.getRule_Predicate();

    /**
     * The meta object literal for the '<em><b>Query</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__QUERY = eINSTANCE.getRule_Query();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.PredicateImpl <em>Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.PredicateImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPredicate()
     * @generated
     */
    EClass PREDICATE = eINSTANCE.getPredicate();

    /**
     * The meta object literal for the '<em><b>Functor</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE__FUNCTOR = eINSTANCE.getPredicate_Functor();

    /**
     * The meta object literal for the '<em><b>Term</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE__TERM = eINSTANCE.getPredicate_Term();

    /**
     * The meta object literal for the '<em><b>Nextterm</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE__NEXTTERM = eINSTANCE.getPredicate_Nextterm();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FunctorImpl <em>Functor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FunctorImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFunctor()
     * @generated
     */
    EClass FUNCTOR = eINSTANCE.getFunctor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTOR__NAME = eINSTANCE.getFunctor_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TermImpl <em>Term</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TermImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTerm()
     * @generated
     */
    EClass TERM = eINSTANCE.getTerm();

    /**
     * The meta object literal for the '<em><b>Term</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERM__TERM = eINSTANCE.getTerm_Term();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AtomImpl <em>Atom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AtomImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAtom()
     * @generated
     */
    EClass ATOM = eINSTANCE.getAtom();

    /**
     * The meta object literal for the '<em><b>At</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATOM__AT = eINSTANCE.getAtom_At();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ListImpl <em>List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ListImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getList()
     * @generated
     */
    EClass LIST = eINSTANCE.getList();

    /**
     * The meta object literal for the '<em><b>Ka</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIST__KA = eINSTANCE.getList_Ka();

    /**
     * The meta object literal for the '<em><b>Atom</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST__ATOM = eINSTANCE.getList_Atom();

    /**
     * The meta object literal for the '<em><b>Rest</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST__REST = eINSTANCE.getList_Rest();

    /**
     * The meta object literal for the '<em><b>Kz</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIST__KZ = eINSTANCE.getList_Kz();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RestImpl <em>Rest</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RestImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRest()
     * @generated
     */
    EClass REST = eINSTANCE.getRest();

    /**
     * The meta object literal for the '<em><b>Opt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REST__OPT = eINSTANCE.getRest_Opt();

    /**
     * The meta object literal for the '<em><b>Atom</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REST__ATOM = eINSTANCE.getRest_Atom();

    /**
     * The meta object literal for the '<em><b>Nextatom</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REST__NEXTATOM = eINSTANCE.getRest_Nextatom();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ListOpt1Impl <em>List Opt1</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ListOpt1Impl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getListOpt1()
     * @generated
     */
    EClass LIST_OPT1 = eINSTANCE.getListOpt1();

    /**
     * The meta object literal for the '<em><b>Atom</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST_OPT1__ATOM = eINSTANCE.getListOpt1_Atom();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ListOpt2Impl <em>List Opt2</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ListOpt2Impl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getListOpt2()
     * @generated
     */
    EClass LIST_OPT2 = eINSTANCE.getListOpt2();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ListOpt3Impl <em>List Opt3</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ListOpt3Impl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getListOpt3()
     * @generated
     */
    EClass LIST_OPT3 = eINSTANCE.getListOpt3();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FolgeImpl <em>Folge</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FolgeImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFolge()
     * @generated
     */
    EClass FOLGE = eINSTANCE.getFolge();

    /**
     * The meta object literal for the '<em><b>Atom</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOLGE__ATOM = eINSTANCE.getFolge_Atom();

    /**
     * The meta object literal for the '<em><b>Nextatom</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOLGE__NEXTATOM = eINSTANCE.getFolge_Nextatom();

  }

} //MyDslPackage
