/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Predicate#getFunctor <em>Functor</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Predicate#getTerm <em>Term</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Predicate#getNextterm <em>Nextterm</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPredicate()
 * @model
 * @generated
 */
public interface Predicate extends EObject
{
  /**
   * Returns the value of the '<em><b>Functor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Functor</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Functor</em>' containment reference.
   * @see #setFunctor(Functor)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPredicate_Functor()
   * @model containment="true"
   * @generated
   */
  Functor getFunctor();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Predicate#getFunctor <em>Functor</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Functor</em>' containment reference.
   * @see #getFunctor()
   * @generated
   */
  void setFunctor(Functor value);

  /**
   * Returns the value of the '<em><b>Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Term</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Term</em>' containment reference.
   * @see #setTerm(Term)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPredicate_Term()
   * @model containment="true"
   * @generated
   */
  Term getTerm();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Predicate#getTerm <em>Term</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Term</em>' containment reference.
   * @see #getTerm()
   * @generated
   */
  void setTerm(Term value);

  /**
   * Returns the value of the '<em><b>Nextterm</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Term}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nextterm</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nextterm</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPredicate_Nextterm()
   * @model containment="true"
   * @generated
   */
  EList<Term> getNextterm();

} // Predicate
