/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prologdsl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Prologdsl#getProgam <em>Progam</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Prologdsl#getExquery <em>Exquery</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPrologdsl()
 * @model
 * @generated
 */
public interface Prologdsl extends EObject
{
  /**
   * Returns the value of the '<em><b>Progam</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Progam</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Progam</em>' containment reference.
   * @see #setProgam(Program)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPrologdsl_Progam()
   * @model containment="true"
   * @generated
   */
  Program getProgam();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Prologdsl#getProgam <em>Progam</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Progam</em>' containment reference.
   * @see #getProgam()
   * @generated
   */
  void setProgam(Program value);

  /**
   * Returns the value of the '<em><b>Exquery</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exquery</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exquery</em>' containment reference.
   * @see #setExquery(Exquery)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPrologdsl_Exquery()
   * @model containment="true"
   * @generated
   */
  Exquery getExquery();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Prologdsl#getExquery <em>Exquery</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exquery</em>' containment reference.
   * @see #getExquery()
   * @generated
   */
  void setExquery(Exquery value);

} // Prologdsl
