/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Query</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Query#getPredicate <em>Predicate</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Query#getNextpredicate <em>Nextpredicate</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getQuery()
 * @model
 * @generated
 */
public interface Query extends EObject
{
  /**
   * Returns the value of the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Predicate</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predicate</em>' containment reference.
   * @see #setPredicate(Predicate)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getQuery_Predicate()
   * @model containment="true"
   * @generated
   */
  Predicate getPredicate();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Query#getPredicate <em>Predicate</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predicate</em>' containment reference.
   * @see #getPredicate()
   * @generated
   */
  void setPredicate(Predicate value);

  /**
   * Returns the value of the '<em><b>Nextpredicate</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Predicate}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nextpredicate</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nextpredicate</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getQuery_Nextpredicate()
   * @model containment="true"
   * @generated
   */
  EList<Predicate> getNextpredicate();

} // Query
